api_keys:
  gpt-3.5-turbo:    
    - api_key: sk-XXXX
      base_url: https://example.com/v1/
      model: gpt-3.5-turbo
  gpt-3.5-turbo-16k:
    - api_key: sk-XXXX
      base_url: https://example.com/v1/
      api_type: azure
      api_version: XXX
      engine: GPT-35-Turbo-16k
      # you can use any kwargs supported by openai.ChatCompletion here
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-3.5-turbo-16k
  gpt-4:    
    - api_key: sk-XXXX
      base_url: https://example.com/v1/
      model: gpt-4
  gpt-4-1106:    
    - api_key: sk-XXXX
      base_url: https://example.com/v1/
      model: gpt-4-1106
  gpt-4-32k:
    - api_key: sk-XXXX
      base_url: https://example.com/v1/
      api_type: XXX
      api_version: XXX
      engine: gpt4-32

default_completion_kwargs:
  model: gpt-3.5-turbo
  temperature: 0.2
  request_timeout: 60

repo_path: /path/to/your/local/repo
project_hierarchy: .project_hierarchy.json
Markdown_Docs_folder: Markdown_Docs # Please pay attention to the way the path is written. Do not add a slash cuz the absolute path is written starting with a slash.
ignore_list: ["ignore_file1.py", "ignore_file2.py", "ignore_directory"] # optional and if needed, relative to repo_path

language: zh